services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn app:app'
    build:
      commands:
        - cp template_file/names.xlsx /opt/render/project/src/template_file/names.xlsx
